In [1]:
'''
Pandas
----------
- Data Cleaning, Data Analysis, Data Visualization, Machine Learning
- File Handling (Text, CSV, Dictionary, JSON)
'''

'\nPandas\n----------\n- Data Cleaning, Data Analysis, Data Visualization, Machine Learning\n- File Handling (Text, CSV, Dictionary, JSON)\n'

In [2]:
import pandas as pd

In [3]:
# Series (1D) and DataFrame (2D)
numbers = pd.Series([1, 2, 3, 4, 5, 6])
numbers

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [4]:
personal_details = pd.DataFrame([
    ['Ram', 30, 'Kathmandu', 40000, 'Bachelors'],
    ['Shyam', 20, 'Kathmandu', 20000, 'Bachelors'],
    ['Hari', 50, 'Laitpur', 100000, 'Masters'],
    ['Bob', 26, 'Bhaktapur', 50000, 'Masters']
], columns=['Name', 'Age', 'Address', 'Salary', 'Qualification'],
   index=['A', 'B', 'C', 'D'])
    # columns=['Name', 'Age', 'Address', 'Salary', 'Qualification'],
    # index=['A', 'B', 'C', 'D'])
personal_details

    Name  Age    Address  Salary Qualification
A    Ram   30  Kathmandu   40000     Bachelors
B  Shyam   20  Kathmandu   20000     Bachelors
C   Hari   50    Laitpur  100000       Masters
D    Bob   26  Bhaktapur   50000       Masters

## Pandas Slicing

In [5]:
'''
loc -> location (While extracting data using alphabetical index)
iloc -> integer location (While extracting data using numerical index)
'''

'\nloc -> location (While extracting data using alphabetical index)\niloc -> integer location (While extracting data using numerical index)\n'

In [6]:
numbers[1:3]

1    2
2    3
dtype: int64

In [7]:
personal_details.iloc[0:3, 1:3]

   Age    Address
A   30  Kathmandu
B   20  Kathmandu
C   50    Laitpur

In [8]:
personal_details.loc['A':'D', 'Salary':'Qualification']

   Salary Qualification
A   40000     Bachelors
B   20000     Bachelors
C  100000       Masters
D   50000       Masters

In [9]:
personal_details.loc[
    ['B', 'D'],
    ['Address', 'Qualification']
]

     Address Qualification
B  Kathmandu     Bachelors
D  Bhaktapur       Masters

In [10]:
personal_details.iloc[
    [1, 3],
    [2, 4]
]

     Address Qualification
B  Kathmandu     Bachelors
D  Bhaktapur       Masters

In [11]:
personal_details.shape

(4, 5)

In [12]:
personal_details.size

20

In [13]:
personal_details.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, A to D
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           4 non-null      object
 1   Age            4 non-null      int64
 2   Address        4 non-null      object
 3   Salary         4 non-null      int64
 4   Qualification  4 non-null      object
dtypes: int64(2), object(3)
memory usage: 364.0+ bytes

In [14]:
'''
csv -> read_csv(file_name)
excel -> read_excel(file_name)
JSON -> read_json(file_name)
'''

'\ncsv -> read_csv(file_name)\nexcel -> read_excel(file_name)\nJSON -> read_json(file_name)\n'

In [15]:
df = pd.read_csv('Dataset/Employees.csv')
df_excel = pd.read_excel('Dataset/EMPLOYEES.xlsx')
# pip install openpyxl

In [16]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [17]:
df.tail()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [18]:
df_excel.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0

In [19]:
df.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [21]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [22]:
'''
# What are the data types in data file?
-> Int, str, float, boolean, None, Complex, Date

# What are the types of data in data file?
-> Numeric and Categorical
'''

'\n# What are the data types in data file?\n-> Int, str, float, boolean, None, Complex, Date\n\n# What are the types of data in data file?\n-> Numeric and Categorical\n'

## Conditional Filtering

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [25]:
# Find details of employees who earns more than 11000.
# select * from employees where salary > 11000;
emp_sal = df['SALARY'] > 11000
df[emp_sal]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,8/17/2002,FI_MGR,12008,NaN,101.0,100.0
45,145,John,Russell,JRUSSEL,011.44.1344.429268,10/1/2004,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,1/5/2005,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,3/10/2005,SA_MAN,12000,0.30,100.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,3/11/2005,SA_REP,11500,0.25,148.0,80.0
101,201,Michael,Hartstein,MHARTSTE,515.123.5555,2/17/2004,MK_MAN,13000,NaN,100.0,20.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0

In [26]:
emp_sal = df[df['SALARY'] > 11000]
emp_sal

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,8/17/2002,FI_MGR,12008,NaN,101.0,100.0
45,145,John,Russell,JRUSSEL,011.44.1344.429268,10/1/2004,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,1/5/2005,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,3/10/2005,SA_MAN,12000,0.30,100.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,3/11/2005,SA_REP,11500,0.25,148.0,80.0
101,201,Michael,Hartstein,MHARTSTE,515.123.5555,2/17/2004,MK_MAN,13000,NaN,100.0,20.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0

In [27]:
# Find details of employees who works in department 50 and earns more than 5000.
dep_sal = df[(df['DEPARTMENT_ID'] == 50) & (df['SALARY'] > 5000)]
dep_sal

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
20,120,Matthew,Weiss,MWEISS,650.123.1234,7/18/2004,ST_MAN,8000,NaN,100.0,50.0
21,121,Adam,Fripp,AFRIPP,650.123.2234,4/10/2005,ST_MAN,8200,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,5/1/2003,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10/10/2005,ST_MAN,6500,NaN,100.0,50.0
24,124,Kevin,Mourgos,KMOURGOS,650.123.5234,11/16/2007,ST_MAN,5800,NaN,100.0,50.0

In [28]:
# Find details of employees who works either in job SA_MAN or IT_PROG.
emp_job = df[(df['JOB_ID'] == 'SA_MAN') | (df['JOB_ID'] == 'IT_PROG')]
emp_job

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2/5/2006,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2/7/2007,IT_PROG,4200,NaN,103.0,60.0
45,145,John,Russell,JRUSSEL,011.44.1344.429268,10/1/2004,SA_MAN,14000,0.4,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,1/5/2005,SA_MAN,13500,0.3,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,3/10/2005,SA_MAN,12000,0.3,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,10/15/2007,SA_MAN,11000,0.3,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,1/29/2008,SA_MAN,10500,0.2,100.0,80.0

In [29]:
# Find details of employees whose salary is in range of 1000 to 5000.
emp_sal_bet = df[df['SALARY'].between(1000, 5000)]
emp_sal_bet

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2/5/2006,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2/7/2007,IT_PROG,4200,NaN,103.0,60.0
15,115,Alexander,Khoo,AKHOO,515.127.4562,5/18/2003,PU_CLERK,3100,NaN,114.0,30.0
16,116,Shelli,Baida,SBAIDA,515.127.4563,12/24/2005,PU_CLERK,2900,NaN,114.0,30.0
17,117,Sigal,Tobias,STOBIAS,515.127.4564,7/24/2005,PU_CLERK,2800,NaN,114.0,30.0
18,118,Guy,Himuro,GHIMURO,515.127.4565,11/15/2006,PU_CLERK,2600,NaN,114.0,30.0
19,119,Karen,Colmenares,KCOLMENA,515.127.4566,8/10/2007,PU_CLERK,2500,NaN,114.0,30.0
25,125,Julia,Nayer,JNAYER,650.124.1214,7/16/2005,ST_CLERK,3200,NaN,120.0,50.0
26,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,9/28/2006,ST_CLERK,2700,NaN,120.0,50.0
27,127,James,Landry,JLANDRY,650.124.1334,1/14/2007,ST_CLERK,2400,NaN,120.0,50.0
28,128,Steven,Markle,SMARKLE,650.124.1434,3/8/2008,ST_CLERK,2200,NaN,120.0,50.0
29,129,Laura,Bissot,LBISSOT,650.124.5234,8/20/2005,ST_CLERK,3300,NaN,121.0,50.0
30,130,Mozhe,Atkinson,MATKINSO,650.124.6234,10/30/2005,ST_CLERK,2800,NaN,121.0,50.0
31,131,James,Marlow,JAMRLOW,650.124.7234,2/16/2005,ST_CLERK,2500,NaN,121.0,50.0
32,132,TJ,Olson,TJOLSON,650.124.8234,4/10/2007,ST_CLERK,2100,NaN,121.0,50.0
33,133,Jason,Mallin,JMALLIN,650.127.1934,6/14/2004,ST_CLERK,3300,NaN,122.0,50.0
34,134,Michael,Rogers,MROGERS,650.127.1834,8/26/2006,ST_CLERK,2900,NaN,122.0,50.0
35,135,Ki,Gee,KGEE,650.127.1734,12/12/2007,ST_CLERK,2400,NaN,122.0,50.0
36,136,Hazel,Philtanker,HPHILTAN,650.127.1634,2/6/2008,ST_CLERK,2200,NaN,122.0,50.0
37,137,Renske,Ladwig,RLADWIG,650.121.1234,7/14/2003,ST_CLERK,3600,NaN,123.0,50.0
38,138,Stephen,Stiles,SSTILES,650.121.2034,10/26/2005,ST_CLERK,3200,NaN,123.0,50.0
39,139,John,Seo,JSEO,650.121.2019,2/12/2006,ST_CLERK,2700,NaN,123.0,50.0
40,140,Joshua,Patel,JPATEL,650.121.1834,4/6/2006,ST_CLERK,2500,NaN,123.0,50.0
41,141,Trenna,Rajs,TRAJS,650.121.8009,10/17/2003,ST_CLERK,3500,NaN,124.0,50.0
42,142,Curtis,Davies,CDAVIES,650.121.2994,1/29/2005,ST_CLERK,3100,NaN,124.0,50.0
43,143,Randall,Matos,RMATOS,650.121.2874,3/15/2006,ST_CLERK,2600,NaN,124.0,50.0
44,144,Peter,Vargas,PVARGAS,650.121.2004,7/9/2006,ST_CLERK,2500,NaN,124.0,50.0
80,180,Winston,Taylor,WTAYLOR,650.507.9876,1/24/2006,SH_CLERK,3200,NaN,120.0,50.0
81,181,Jean,Fleaur,JFLEAUR,650.507.9877,2/23/2006,SH_CLERK,3100,NaN,120.0,50.0
82,182,Martha,Sullivan,MSULLIVA,650.507.9878,6/21/2007,SH_CLERK,2500,NaN,120.0,50.0
83,183,Girard,Geoni,GGEONI,650.507.9879,2/3/2008,SH_CLERK,2800,NaN,120.0,50.0
84,184,Nandita,Sarchand,NSARCHAN,650.509.1876,1/27/2004,SH_CLERK,4200,NaN,121.0,50.0
85,185,Alexis,Bull,ABULL,650.509.2876,2/20/2005,SH_CLERK,4100,NaN,121.0,50.0
86,186,Julia,Dellinger,JDELLING,650.509.3876,6/24/2006,SH_CLERK,3400,NaN,121.0,50.0
87,187,Anthony,Cabrio,ACABRIO,650.509.4876,2/7/2007,SH_CLERK,3000,NaN,121.0,50.0
88,188,Kelly,Chung,KCHUNG,650.505.1876,6/14/2005,SH_CLERK,3800,NaN,122.0,50.0
89,189,Jennifer,Dilly,JDILLY,650.505.2876,8/13/2005,SH_CLERK,3600,NaN,122.0,50.0
90,190,Timothy,Gates,TGATES,650.505.3876,7/11/2006,SH_CLERK,2900,NaN,122.0,50.0
91,191,Randall,Perkins,RPERKINS,650.505.4876,12/19/2007,SH_CLERK,2500,NaN,122.0,50.0
92,192,Sarah,Bell,SBELL,650.501.1876,2/4/2004,SH_CLERK,4000,NaN,123.0,50.0
93,193,Britney,Everett,BEVERETT,650.501.2876,3/3/2005,SH_CLERK,3900,NaN,123.0,50.0
94,194,Samuel,McCain,SMCCAIN,650.501.3876,7/1/2006,SH_CLERK,3200,NaN,123.0,50.0
95,195,Vance,Jones,VJONES,650.501.4876,3/17/2007,SH_CLERK,2800,NaN,123.0,50.0
96,196,Alana,Walsh,AWALSH,650.507.9811,4/24/2006,SH_CLERK,3100,NaN,124.0,50.0
97,197,Kevin,Feeney,KFEENEY,650.507.9822,5/23/2006,SH_CLERK,3000,NaN,124.0,50.0
98,198,Donald,OConnell,DOCONNEL,650.507.9833,6/21/2007,SH_CLERK,2600,NaN,124.0,50.0
99,199,Douglas,Grant,DGRANT,650.507.9844,1/13/2008,SH_CLERK,2600,NaN,124.0,50.0
100,200,Jennifer,Whalen,JWHALEN,515.123.4444,9/17/2003,AD_ASST,4400,NaN,101.0,10.0

In [30]:
# Find details of employees who works either in job SA_MAN or IT_PROG.
emp_job_or = df[df['JOB_ID'].isin(['SA_MAN', 'IT_PROG'])]
emp_job_or[['FIRST_NAME', 'LAST_NAME', 'JOB_ID', 'SALARY', 'DEPARTMENT_ID']]

   FIRST_NAME  LAST_NAME   JOB_ID  SALARY  DEPARTMENT_ID
3   Alexander     Hunold  IT_PROG    9000           60.0
4       Bruce      Ernst  IT_PROG    6000           60.0
5       David     Austin  IT_PROG    4800           60.0
6       Valli  Pataballa  IT_PROG    4800           60.0
7       Diana    Lorentz  IT_PROG    4200           60.0
45       John    Russell   SA_MAN   14000           80.0
46      Karen   Partners   SA_MAN   13500           80.0
47    Alberto  Errazuriz   SA_MAN   12000           80.0
48     Gerald  Cambrault   SA_MAN   11000           80.0
49      Eleni    Zlotkey   SA_MAN   10500           80.0

In [31]:
hr = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [32]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [33]:
# NaN -> Not a Number
# NaT -> Not a Time

In [48]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [35]:
'''
dropna(axis=0(default)/1, how='any' (default)/'all', inplace=True/False(default))
--------------------
axis
    -> 0 -> Row
    -> 1 -> Column

how
    -> any -> one or many null values
    -> all -> all data must be null
'''

"\ndropna(axis=0(default)/1, how='any' (default)/'all', inplace=True/False(default))\n--------------------\naxis\n    -> 0 -> Row\n    -> 1 -> Column\n\nhow\n    -> any -> one or many null values\n    -> all -> all data must be null\n"

In [36]:
# Inplace=True -> Make changes permanently
df.dropna(axis=1, how='any', inplace=True)

In [37]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000
...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300

In [44]:
df.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

In [76]:
# fillna(value, inplace=True/False(default))
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

In [45]:
mean_comm = df['COMMISSION_PCT'].mean()
median_comm = df['COMMISSION_PCT'].median()

print(mean_comm)
print(median_comm)

0.22285714285714284
0.2

In [51]:
# df['COMMISSION_PCT'].fillna(median_comm, inplace=True)
df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(median_comm)

In [54]:
df['COMMISSION_PCT'].unique()

array([0.2 , 0.4 , 0.3 , 0.25, 0.15, 0.35, 0.1 ])

In [77]:
mgr_mode = df['MANAGER_ID'].mode()[0]

In [78]:
dep_mode = df['DEPARTMENT_ID'].mode()[0]
dep_mode

np.float64(50.0)

In [79]:
df['MANAGER_ID'] = df['MANAGER_ID'].fillna(mgr_mode)

In [80]:
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].fillna(dep_mode)

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    datetime64[ns]
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  111 non-null    float64
 9   MANAGER_ID      111 non-null    int64
 10  DEPARTMENT_ID   111 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 9.7+ KB

### Change datatypes

In [90]:
df['MANAGER_ID'] = df['MANAGER_ID'].astype(int)

In [92]:
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].astype(int)

In [ ]:
'''
DateTime
------------
2/21/2001
2001/04/23
2003-04-5

Format
---------
'%d.%m.%y'
'%d-%m-%y'
'mixed'
'''

In [96]:
df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'], format='%d.%m.%y')

### Skewness and Kurtosis

In [ ]:
## Skewness
'''
    postive skewness -> right skewness -> number of low values are more
    negative skewness -> left skewness -> number of high values are more
    zero -> normal distribution -> high and low value both are equal
'''

In [98]:
df['SALARY'].skew()

np.float64(1.2472700500786322)

In [ ]:
'''
High Kurtosis -> High Outlier
Low Kurtosis -> Flatter distribution
'''

In [99]:
df['SALARY'].kurt()

np.float64(2.7253459912431084)

## String Replace

In [100]:
# ./?<>,.(){}[]:";'!@#$%^&*()_+-= -> regular expressions (regex)

In [101]:
# str.replace(find, replace_value, regex=False)
df['PHONE_NUMBER'] = df['PHONE_NUMBER'].str.replace('-', '', regex=False)

In [103]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515-123-4567,2003-06-17,AD_PRES,24000,0.2,100,90
1,101,Neena,Kochhar,NKOCHHAR,515-123-4568,2005-09-21,AD_VP,17000,0.2,100,90
2,102,Lex,De Haan,LDEHAAN,515-123-4569,2001-01-13,AD_VP,17000,0.2,100,90
3,103,Alexander,Hunold,AHUNOLD,590-423-4567,2006-01-03,IT_PROG,9000,0.2,102,60
4,104,Bruce,Ernst,BERNST,590-423-4568,2007-05-21,IT_PROG,6000,0.2,103,60
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515-123-8181,2002-06-07,AC_ACCOUNT,8300,0.2,205,110
107,203,Susan,Mavris,SMAVRIS,515-123-7777,2002-06-07,HR_REP,6500,0.2,101,40
108,204,Hermann,Baer,HBAER,515-123-8888,2002-06-07,PR_REP,10000,0.2,101,70
109,205,Shelley,Higgins,SHIGGINS,515-123-8080,2002-06-07,AC_MGR,12008,0.2,101,110
110,206,William,Gietz,WGIETZ,515-123-8181,2002-06-07,AC_ACCOUNT,8300,0.2,205,110